### PR TITLE
Implementation of annotation ID option in objects getters

### PR DESCRIPTION
**Pull request by Tom-TBT**
## Description
Hello,
this implements an optional annotation parameter for the object getters. Providing an annotation ID, it retrieves the IDs of objects annotated with this annotation.

```
# Return IDs of all images annotated with Tag ID 876:
 >>> tag_ims = get_image_ids(conn, annotation=876)
```

This is my other attempt to get objects by annotations, instead of https://github.com/TheJacksonLaboratory/ezomero/pull/88. In this case, I don't have a new function and I use HQL queries.

Feedback very much appreciated and thank you for your time

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py) 
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.

### CODE REVIEW

**Comment by erickmartins** [comment]
(just FYI, I am will be on vacation for the next 3 weeks, so reviewing this might be a while!)

**Comment by erickmartins** [comment]
ok, I think I understand this use case now and I'm on board with adding this. I'll make some time tomorrow to review code in a bit more detail, but I think this does allow for things that a simple `filter_by_annotation()` would. (I also think we should replace `filter_by_tag_value()` and `filter_by_kv()` by a generic `filter_by_annotation()` that would allow generic filtering of ID lists by "which ones are linked to a given annotation ID", but that can wait)

**Comment by Tom-TBT** [comment]
This is great, I am glad that you are on board. 
I will be away for two weeks for some holidays, so I'll look at your review when I'm back

Cheers

**Review by erickmartins — APPROVED** [review]
Nothing to add or change on my end - I'll wait until you're back from vacation to merge it just in case

**Comment by Tom-TBT** [comment]
Hey Erick, I'm back from my holidays. I don't have any comment to add. You can go ahead.

**Pull request merged**
