### PR TITLE
Getters for High-Content-Sreening

### PR DESCRIPTION
**Pull request by Tom-TBT**
## Description

The PR implements getters for `Screen`, `Plate`, `Run`, and `Well`, in the same style as the `Project`, `Dataset`, and `Image` getters.

I implemented tests to cover the new getter functions, for which I modified the generated screen.

There is in addition a new option for `get_image_ids`, to list images according to a Run ID. This could be a breaking change for anyone who specifies each parameter without their name. (I did that for the sake of consistency for the options order)

Breaking change case, the `across_groups` parameter was passed without its name:
`get_image_ids(conn, None, None, 12, None, False)`
This would now return a `TypeError('Run ID must be integer')` as the `False` value gets into the `run` parameter.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.

### CODE REVIEW

**Comment by erickmartins** [comment]
(this is just a message to acknowledge I've seen this and #102  - will get to these as soon as I have some time!

**Comment by erickmartins** [comment]
picking nits: I think I'd rather have everything be `plate_acquisition` instead of `run` - the OME data model object is `PlateAcquisition` and I'd rather stick to the data model whenever possible!

**Comment by Tom-TBT** [comment]
I'll write here in case you haven't got a notification, I pushed changes to replace `run` with `plate_acquisition`  :D

**Comment by erickmartins** [comment]
Merged - thanks for the patience (and sorry for the communication issues!)

**Pull request merged**
